#!/usr/bin/python3

"""
count's a users commits to a specific repository

Author: Bradley Dillion Gilden
Date: 29-09-2023
"""
import sys
import requests


if __name__ == '__main__':
    repo = sys.argv[1]
    headers = {
        "X-GitHub-Api-Version": "2022-11-28",
        "Authorization": "Bearer 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",
        "Accept": "application/vnd.github+json"
    }
    name_count = {}

    response = requests.get(
        f'https://api.github.com/repos/BradleyGilden/{repo}/commits', headers=headers
        )
    try:
        for user in response.json():
            user_name = user.get('commit').get('author').get('name')
            if user_name in name_count.keys():
                name_count[user_name] += 1
            else:
                name_count[user_name] = 0
        for k, v in name_count.items():
            print(f"{k}: {v}")
    except Exception:
        pass
