#!/bin/bash

while read -r file
do
    touch "$file"
    chmod +x "$file"
    current_date=$(date +%d-%m-%Y)
    echo '#!/usr/bin/python3' > "$file"
    echo "
\"\"\"
<module docstring>

Author: Bradley Dillion Gilden
Date: $current_date
\"\"\"" >> "$file"
    printf "\n\n" >> "$file"
    echo "if __name__ == '__main__':" >> "$file"
done
